title: Dennis McClimans # your name (or website title) here
logo: "images/A8EF35F0-33E0-47A2-9597-1B64531BA6B4.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my Github page. I am a Geography and Environmental Systems BA student with the GIS certificate at University of Maryland, Baltimore county.   
  <br><br>
  After graduation I am moving to San Antonio, Texas to work as a project manager. I'm hoping to intergrate GIS technologies into the company I work for. 
  <br><br>
  <a href="https://www.linkedin.com/in/dennis-mcclimans-1624b668/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
