title: Dennis McClimans # your name (or website title) here
logo: "/images/henry.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  Hey! I am Dennis R McClimans and I am a student at UMBC. I am almost finished with my B.A. in Geography and Environmental Studies with a certificate in GIS. 
  <br><br>
  Second description
  I work at JHU APL and Live in Towson, Maryland. 
  <br><br>
  <a href="https://www.linkedin.com/in/dennis-mcclimans-1624b668/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
